### ISSUE TITLE
[Feature request] Make "All Tags" and "Dataset" lists to remember their last position, when making changes

### ISSUE THREAD

**Issue by neojam** [starik222/BooruDatasetTagManager#10]
Hallo,

can you please make both lists ("Dataset" and "All Tags") to remember their last position/selection, when you make any changes?

For "All tags" list:
Currently when you click on "Apply"-Button on the "Image tags" list, the "All tags" list gets refreshed and it's position returns to the first tag on the list. It would be great, if instead it would return to the last selected tag on the "All tags" list.
If the last selected tag is no longer on the "All tags" list and can't be found, because it was completely deleted from Dataset, then the "All tags" list should return to the last known **position** of the deleted tag instead (the row number on "All tags" list).

Also it would be great, when in "All tags" list you press some keyboard key for example "T", the position would jump to the first tag starting with letter "t". This would help to navigate in the list faster.

For "Dataset" thumbnail list:
When you click on "Reset filter" button, the position of the "Dataset" list should return to the last selected thumb/element. If several thumbs were selected, then to the most bottom one.

**Optional** (only if you have time to implement it):
If several tags were selected on "All Tags" list before making changes, it would be great if all previously selected tags were remembered.
That way you can select several tags in the "All tags" list, then select several images from "Dataset" list and add/remove the selected tags to that group of images. After saving changes, you can select another group of Images from "Dataset" and then add/remove the same selected tags again. Currently its possible to do only once, since the selection of tags get lost after the first time you make/save changes and then you have to reselect the tags again.

Those changes would greatly help with the workflow and productivity when cleaning or adding tags for the "All tags" list.

Thank you!

Also an unrelated question:
What are those files are for?
ReplaceChar.txt
ReplaceNames.txt
ReplaceText.txt
I cant find any documentation for those. Can those be used for auto-replacing tags? (its what the filenames seem to suggest)

**Comment by starik222** [comment]
> Also an unrelated question:
What are those files are for?
ReplaceChar.txt
ReplaceNames.txt
ReplaceText.txt
I cant find any documentation for those. Can those be used for auto-replacing tags? (its what the filenames seem to suggest)

These files are linked to the[ translator.dll](https://github.com/starik222/Translator) library. This is a shared library for my other applications that use machine translation and these files serve to improve it. In the same application, they are not used in any way.

**Comment by starik222** [comment]
Implemented in 1.6.0

**Comment by neojam** [comment]
Thanks a lot man :)
Just in time for my next LoRA project
