### ISSUE TITLE
\r\n as Separator Fails

### ISSUE THREAD

**Issue by RexLeeGrey** [starik222/BooruDatasetTagManager#105]
In the latest version under Windows, the newline character \r\n as a separator is ineffective and cannot be used for splitting.
![image](https://github.com/starik222/BooruDatasetTagManager/assets/125941057/0cc075f1-0dcd-4fb6-a7fe-eb30479328d5)

**Comment by starik222** [comment]
Please explain where you use the line break character? Do you separate tags in text files line by line?

**Comment by RexLeeGrey** [comment]
![image](https://github.com/starik222/BooruDatasetTagManager/assets/125941057/b9515803-687f-414b-9ff4-f26a614b50ff)
like this

**Comment by starik222** [comment]
Implemented in [2.0.3](https://github.com/starik222/BooruDatasetTagManager/releases/tag/v2.0.3)
