### ISSUE TITLE
Program automatically formats tags with unwanted backslashes

### ISSUE THREAD

**Issue by madman404** [starik222/BooruDatasetTagManager#108]
Hello! I am trying out the newest version of the program to take advantage of the addition of hotkeys for faster tagging, but I can't help but notice that the features to remove automatic formatting of tags (for example, parenthesis having a backslash added) was removed. This is a big issue to me, as I do not need or want any automatic formatting on my completed captions, and now I need to go back over my datasets with an older version of the program for the express purpose of cleaning up these erroneously "fixed" tags.

Will this feature be added back again at some point? If not, why was it even removed?

**Comment by starik222** [comment]
To parse text prompts, an algorithm was taken from stable-diffusion-webui. The same algorithm is used in other training scripts, like kohya_ss. This was done to implement weighted tag support. Accordingly, if the text files contained tags with brackets without backslashes, these brackets will be converted to weights. Brackets with backslashes will be displayed as regular brackets in the editor and will also be saved with backslashes.
Can you give an example where pure brackets that are not a weight modifier were used for training?

**Comment by madman404** [comment]
An example would be sd-scripts (the backend Kohya_ss runs on). The default behavior for the program is to _not_ use weighted captions, with weighted captions being an alternative option I have not experimented with at all. With default settings, I have to clear out all the backslashes or they will be trained as part of the caption.

Additionally, the booru autocaptioning models I use output tags as a comma delineated list with un-escaped parenthesis, and loading those autocaptions into the program for refining causes them to break up and have backslashes added to them as well. Ideally, I'd just like to have a single option I can click to turn off the processing so that the tags I see are the tags I get.

**Comment by starik222** [comment]
Implemented in [2.0.3](https://github.com/starik222/BooruDatasetTagManager/releases/tag/v2.0.3)
