### ISSUE TITLE
Can't double-click .exe to start program

### ISSUE THREAD

**Issue by SirMoogle** [starik222/BooruDatasetTagManager#109]
For some reason I'm unable to open the manager by double-clicking on the .exe. I unzipped the folder, made sure it was trusted by my antivirus, and that it wasn't read-only or something similar. My workaround is to open Command Prompt in the directory and launch it from there. I'm running this on a Windows 11.

**Comment by starik222** [comment]
This is some kind of problem in your operating system and has nothing to do with the program.
