### ISSUE TITLE
About adding translation function

### ISSUE THREAD

**Issue by 1dadou1** [starik222/BooruDatasetTagManager#110]
Is it possible to implement an automatic translation from the native language to English when adding new tags? Alternatively, adding a translation button in the tag input area could save a lot of time while entering tags. This could be achieved by integrating a translation API, where users can apply for their own API key to enable the translation feature. Currently, there are many translation APIs available, such as BaiduTranslator, DeeplTranslator, QcriTranslator, DetectLanguage, ChatGptTranslator, AliTranslation, etc.

**Comment by starik222** [comment]
What don't you like about the current translator? It has a small bug where the translation of changed tags is updated when the image is reselected, but otherwise it works fine.

**Comment by starik222** [comment]
Honestly, I don't see the point in this. The editor has a function for translating tags from English into the selected language to facilitate their editing. You can also translate tags in the auto-completion list. You can set up a search for tags in the auto-completion list by translation. WDTagger, Blip and other autotaggers generate text in English. If you want to write texts in your native language and translate them into English, then this is much easier to do in the interface of the translator itself.
