### ISSUE TITLE
"Set current tag to all images" button is actually a "Set current tag list to all images"

### ISSUE THREAD

**Issue by gpl666** [starik222/BooruDatasetTagManager#119]
Nothing more than that: i thought that that was a function to copy the currently selected tag in the current image to every other image in the dataset, but instead it takes all the tags of the current image, even the unselected ones, and replaces all other tag lists with this one, so every image ends in having the same tag list. Also this operation is not undoable so i've lost hours of work :( I think it could be a good idea to rename it correctly
Image:
![image](https://github.com/starik222/BooruDatasetTagManager/assets/39886532/308aea4b-0c73-4a95-9c2d-7b0ab4a67ac8)

**Comment by starik222** [comment]
Fixed in [2.2.0](https://github.com/starik222/BooruDatasetTagManager/releases/tag/v2.2.0)

**Comment by gpl666** [comment]
> Fixed in [2.2.0](https://github.com/starik222/BooruDatasetTagManager/releases/tag/v2.2.0)

Thank you very much!
