### ISSUE TITLE
[Feature request] translation with replace '_' to ' ' and load translation csv

### ISSUE THREAD

**Issue by sdbds** [starik222/BooruDatasetTagManager#12]
1.some tagger like WD14Tagger use '_' other than ' '
sometimes translator not work

2.if we can load tagger datesets csv,we can directly translate tags to other languages,not need more network

**Comment by starik222** [comment]
1. implemented in 1.6.0
2. I see no reason to translate more than 160 thousand tags, 99% of which will not be used, and the translation will take a lot of time.
