### ISSUE TITLE
[Feature Request] Add hotkey to focus on preview

### ISSUE THREAD

**Issue by SirMoogle** [starik222/BooruDatasetTagManager#125]
Trying out the most recent version and really appreciate the hotkeys. Would it be possible to add one to focus on the preview pane, like there are for focusing on the image, image tag, and all tags lists?

**Comment by starik222** [comment]
Implemented in [2.2.0](https://github.com/starik222/BooruDatasetTagManager/releases/tag/v2.2.0)
