### ISSUE TITLE
New function request

### ISSUE THREAD

**Issue by w844741652** [starik222/BooruDatasetTagManager#131]
When I open two BoorudatasetTagManagers at the same time, I hope to copy all the TAG of A picture in software A to a picture in software B, which is not possible in 2.1.4 at the present stage
![20240408142308](https://github.com/starik222/BooruDatasetTagManager/assets/39794671/ec30cef8-ae53-4c84-822f-8c558ac2020b)

**Comment by hansolocambo** [comment]
I just did that. And it's already perfectly possible to copy all tags from an opened instance of the app to another.

**Comment by starik222** [comment]
Implemented in [2.2.0](https://github.com/starik222/BooruDatasetTagManager/releases/tag/v2.2.0)
