### ISSUE TITLE
Global tag sorting by count

### ISSUE THREAD

**Issue by Darkenlord1** [starik222/BooruDatasetTagManager#139]
Looked through already asked/answered issues and found this one - https://github.com/starik222/BooruDatasetTagManager/issues/60 but i cant find sorting in global tags. Is it actually implemented?

**Comment by An0925** [comment]
I can't find this function either, really need it!

**Comment by starik222** [comment]
Implemented in [2.3.0](https://github.com/starik222/BooruDatasetTagManager/releases/tag/v2.3.0)

**Comment by An0925** [comment]
> Implemented in [2.3.0](https://github.com/starik222/BooruDatasetTagManager/releases/tag/v2.3.0)

thx so much, you are the lifesaver
