### ISSUE TITLE
[feature request] add linux build

### ISSUE THREAD

**Issue by derVedro** [starik222/BooruDatasetTagManager#14]
Hey, that is a nice tagger, but it's kind unstable running under wine in linux. Can you do a linux native build with mono?

**Comment by derVedro** [comment]
I installed dotnet-runtime 6.0 but could not run it, I guess framework 'Microsoft.WindowsDesktop.App' is not available for linux.

**Comment by starik222** [comment]
Well, this is the problem, Winforms is an add-on for windows, and most likely is not supported in Linux. To port the project, for example, under mono, it will be necessary to do a lot of work. So for now it's not feasible.

**Comment by derVedro** [comment]
Ok, I understand. Жаль, конечно.

**Comment by marshalleq** [comment]
Took a while to find, but for anyone else coming here, this tag manager works well in linux. https://github.com/jhc13/taggui and mac actually, also windows.
