### ISSUE TITLE
Can you please tell us the steps to activate the UI?

### ISSUE THREAD

**Issue by Zakutu** [starik222/BooruDatasetTagManager#140]
Can you please tell us the steps to activate the UI?

**Comment by tyefraser** [comment]
I've added some info on how to open the gui: https://github.com/tyefraser/BooruDatasetTagManager/tree/issue-140-readme_updates
PR: https://github.com/starik222/BooruDatasetTagManager/pull/141

Basically:
This is a tool designed in C and you will need to run it in Visual Studio (not Visual Studio Code). Steps to achieve this are:

Download [visual Studio](https://visualstudio.microsoft.com/downloads/)
Clone this repo into a folder somewhere on your computer
Open the repo using Visual Studio: File > Open > Project/Solution > select the BooruDatasetTagManager.sln file
Build the solution by selecting Build > Build Solution from the menu (or by pressing Ctrl+Shift+B. Run the Application)
Run the application by selecting Debug > Start Without Debugging (or press Ctrl+F5).
You can now interact with the gui application.

**Comment by Zakutu** [comment]
Thank you!
