### ISSUE TITLE
some tag saving problems,

### ISSUE THREAD

**Issue by MinagiCN** [starik222/BooruDatasetTagManager#142]
i met with some tag rename problems,

1, if i have repeated tags in the same txt file,like two "full body" tags,or 3 "1girl"tags, after saving with BooruDatasetTagManager, the content in txt changed into "(full body)" and "((1girl))", I'll have to re-edit it one by one manually,i think auto delete the duplicated tags and remain only one of them would be a better choice.Or can i just turn this function off.

2,if there are tags originally made up with (),  like "poster (object)","chihaya (clothing)" or "painting (action)",, after saving with BooruDatasetTagManager, these tags will be divided into different parts(one tag became two tags),like "poster,object","chihaya,clothing","painting,action",  it doesn't make sense.

Thank you.

**Comment by starik222** [comment]
This is the logic behind how weighted tags work. Moreover, this works when loading, and not when saving, for example, if there are two tags “1girl” in a text file, then one tag “(1girl)” will be loaded into the program. As in WebUI, brackets are a tag weight modifier, and if you want to use them directly in text, they need to be escaped with "\(text\)". You can disable weighted tags by disabling the "Fix tag when loading..." option in the settings.

**Comment by MinagiCN** [comment]
> This is the logic behind how weighted tags work. Moreover, this works when loading, and not when saving, for example, if there are two tags “1girl” in a text file, then one tag “(1girl)” will be loaded into the program. As in WebUI, brackets are a tag weight modifier, and if you want to use them directly in text, they need to be escaped with "\(text\)". You can disable weighted tags by disabling the "Fix tag when loading..." option in the settings.

Thank you!!

**Comment by MinagiCN** [comment]
> This is the logic behind how weighted tags work. Moreover, this works when loading, and not when saving, for example, if there are two tags “1girl” in a text file, then one tag “(1girl)” will be loaded into the program. As in WebUI, brackets are a tag weight modifier, and if you want to use them directly in text, they need to be escaped with "\(text\)". You can disable weighted tags by disabling the "Fix tag when loading..." option in the settings.

sorry for another problem, i want to edit tags in the right "All tags"column, for example i want to change ((1girl)) to 1girl, i clicked "replace tag" button and set new tag to 1girl then click OK, but nothing happens? how can i delete () in All Tag column, Thank you.
