### ISSUE TITLE
[request] Image preview

### ISSUE THREAD

**Issue by Darkenlord1** [starik222/BooruDatasetTagManager#149]
Is it possible to make a toggle button to switch image preview from panel with global tags to a separate window as it was some versions before?

Because as it is right now, for me it is quite scuffed to switch from preview to global tags to add some of them to the images.

**Comment by starik222** [comment]
In the settings you can select a preview mode (either in a separate window or in a tab). There are also hotkeys (default ctrl + 1-5) with which you can switch between windows/tabs.
Or is it not convenient for you to go into settings and you want a special button to change the preview mode?

**Comment by Darkenlord1** [comment]
Ah, i see, thanks!
