### ISSUE TITLE
[BUG] Can't add a tag(s) to multiple selected images in dataset

### ISSUE THREAD

**Issue by neojam** [starik222/BooruDatasetTagManager#15]
Hi, first thanks for the V1.6.0, it really handles nicer :)

But it looks like some things got broken along the way. 
Now i can't add a tag to **multiple** images in dataset. 
There is an error/exception after that, where I can only exit the program.

How to replicate:
- select one or more tags in "All Tags" list
- select **multiple** images in "Dataset" list with CTRL+Leftclick
- Click button "Add selected 'All Tags' to Dataset"
- Click any image in Dataset to save the settings
An error Message will popup.

Same happens if you click on "Add to filtered" button, but only if you don't use filter prior that.

Currently applying tags works only for a one/single selected image, so for now I'm back using v1.5.2.

**Comment by starik222** [comment]
Thank you, fixed in 1.6.1
