### ISSUE TITLE
Replace All function sometimes doesn't work

### ISSUE THREAD

**Issue by a442509097** [starik222/BooruDatasetTagManager#155]
v2.2.1

**Comment by starik222** [comment]
Please describe in more detail, maybe you have a specific example, or some sequence of actions, or at least how often this happens.

**Comment by a442509097** [comment]
> Please describe in more detail, maybe you have a specific example, or some sequence of actions, or at least how often this happens.
Sorry, it's my fault.
My original steps: Click "chair" -> Filter in dataset -> Replace tag "black hair" with "hair".
I should have clicked 'Exit dataset filter' first, and then clicked on 'Replace tag' ( All Tag)

**Comment by a442509097** [comment]
@starik222 

Sorry, it's my fault.
My original steps: Click "chair" -> Filter in dataset -> Replace tag "black hair" with "hair".
I should have clicked 'Exit dataset filter' first, and then clicked on 'Replace tag' ( All Tag)
