### ISSUE TITLE
feature: tag and img

### ISSUE THREAD

**Issue by kalle07** [starik222/BooruDatasetTagManager#160]
if i double click on an image it will be shown in the middle part, now i click once at another image/tag
it only change the tag not the image, i must click twice...

**Comment by starik222** [comment]
Double-clicking an image and enabling image preview are different. If you want the image preview to toggle when you change the selection, simply enable preview in the view menu. Double-clicking opens the preview once (without enabling the preview function)

**Comment by kalle07** [comment]
nop...
same,if i enable preview double-click, ok previev open but if i choose the next image/tag i must allways double-click to update the image of the tag

**Comment by starik222** [comment]
Please watch this video, maybe you will find a solution to your problem in it.
https://youtu.be/276defoX8q8

**Comment by kalle07** [comment]
ah settings,  thx
