### ISSUE TITLE
After the new update the threshold value on autotagger ui is not shown.

### ISSUE THREAD

**Issue by wensleyoliv** [starik222/BooruDatasetTagManager#164]
Both on dark and classic themes, on autotagger ui the threshold value is not shown, making things harder to adjust.
![dark](https://github.com/user-attachments/assets/c8237b6d-71fc-47e2-acc4-5386692b3f12)
![classic](https://github.com/user-attachments/assets/8ae2ec32-39de-4962-ac83-94bb0e9b458c)

**Comment by starik222** [comment]
Fixed in [2.3.1](https://github.com/starik222/BooruDatasetTagManager/releases/tag/v2.3.1)
