### ISSUE TITLE
Dependencies for webp expected in strange folder.

### ISSUE THREAD

**Issue by DalekSkaro1** [starik222/BooruDatasetTagManager#168]
I build the program with Visual Studio 2022, but. when trying to process a folder with the program I get the following error: "Unhandled exception has occurred in your application. If you click Continue, the application will ignore this error and attempt to continue. If you click Quit, the application will close immediately. Unable to load DLL 'Libs\libwebp\x64\libwebp.dll' or one of its dependencies: The specified module could not be found. (0x8007007E) In WebP.GetInfo In WebP.Load.". But, there is no folder "Libs\libwebp\x64\", in fact there can be no such folder in Windows since it does not begin with a letter drive. I tried to create such a folder with the .dll but the program could not find it. I also tried to change the specified folder in the source code and rebuild but the program doesn't seem to find the .dll either way. Also I have put the directory in witch the libwebp.dll is in my PATH variable, and this did not work.

**Comment by starik222** [comment]
Yes, the project does not contain links to native libraries, but they are used in WebPWrapper.cs. You can copy the "Libs" folder from any release to the output folder of your build. The webp library itself is taken from [this repository](https://github.com/JosePineiro/WebP-wrapper). If you want to build native libraries yourself, use [this repository](https://chromium.googlesource.com/webm/libwebp).
