### ISSUE TITLE
Bug automaticly "\", cant edit all tags tab manually

### ISSUE THREAD

**Issue by bayudewan** [starik222/BooruDatasetTagManager#20]
![image](https://user-images.githubusercontent.com/69073547/230993371-8ba85cbc-4400-494f-b0ba-826d27b1bdc2.png)
Everytime i load the dataset images with text files, it always gave me this \  how do i edit the "all tags" manually?

**Comment by bayudewan** [comment]
this sign \

**Comment by starik222** [comment]
Thanks, fixed in 1.6.2.
