### ISSUE TITLE
[Request] Dark mode / Dark theme

### ISSUE THREAD

**Issue by aphaits** [starik222/BooruDatasetTagManager#40]
Would be really helpful on reducing eye fatigue if dark theme / dark gray theme is implemented as an option.
Something similar to Blender's UI color palette.

**Comment by jojje** [comment]
Perhaps [this](https://github.com/jojje/BooruDatasetTagManager/tree/master) suffices?

**Comment by starik222** [comment]
Implemented in version [2.0.0](https://github.com/starik222/BooruDatasetTagManager/releases/tag/v2.0.0)
