### ISSUE TITLE
[Bug] Huge performance bug when selecting multiples images.

### ISSUE THREAD

**Issue by Kuinox** [starik222/BooruDatasetTagManager#42]
On my dataset, selecting multiples images freeze the interface. If I select 5 images it will freeze for 5 seconds, and if I select 10 images it will freeze for 10 seconds.

**Comment by starik222** [comment]
Fixed in [1.6.6](https://github.com/starik222/BooruDatasetTagManager/releases/tag/v1.6.6)

**Comment by Kuinox** [comment]
thx !
