### ISSUE TITLE
[Request] Allow to move menu in different position

### ISSUE THREAD

**Issue by pastuh** [starik222/BooruDatasetTagManager#43]
When working with many tags, it is difficult to activate or remove them, because the buttons "Add tags" and "Remove tags" located on the right side.

- Moving the main menu or part of it would solve the problem. (it could float on the top)
- Duplicating the menu on the left side would also solve the problem

**Comment by starik222** [comment]
Implemented in version [2.0.0](https://github.com/starik222/BooruDatasetTagManager/releases/tag/v2.0.0)
