### ISSUE TITLE
Sequence contains no elements

### ISSUE THREAD

**Issue by Morpheen** [starik222/BooruDatasetTagManager#48]
I've downloaded both available options of the latest release for Windows 10 and both give me the same error. I have the required .NET stuff installed and cannot figure this out. I'm not well versed in developer or programming stuff so I'm sure that's a majprity of my problem. The provided info from the "Details" popup when erroring out:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at BooruDatasetTagManager.DatasetManager.UpdateData() in M:\Dev\BooruDatasetTagManager\BooruDatasetTagManager\DatasetManager.cs:line 72
   at BooruDatasetTagManager.Form1.openFolderToolStripMenuItem_Click(Object sender, EventArgs e) in M:\Dev\BooruDatasetTagManager\BooruDatasetTagManager\Form1.cs:line 100
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.Private.CoreLib.dll
----------------------------------------
BooruDatasetTagManager
    Assembly Version: 1.6.5.0
    Win32 Version: 1.6.5.0
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/BooruDatasetTagManager.dll
----------------------------------------
System.Runtime
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.1423.7402
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.ComponentModel.Primitives.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.1423.7402
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.Collections.Specialized.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.Drawing.Common.dll
----------------------------------------
System.Threading
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.Collections.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.3.27908
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/Newtonsoft.Json.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.Runtime.Serialization.Formatters.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.Collections.Concurrent.dll
----------------------------------------
System.Linq.Expressions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.Linq.Expressions.dll
----------------------------------------
System.Runtime.Numerics
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.Runtime.Numerics.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.Private.Uri.dll
----------------------------------------
System.Linq
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.Linq.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.ObjectModel
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.ObjectModel.dll
----------------------------------------
System.Runtime.Serialization.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.Runtime.Serialization.Primitives.dll
----------------------------------------
System.Data.Common
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.Data.Common.dll
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.Private.Xml.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.ComponentModel.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.Reflection.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.Reflection.Primitives.dll
----------------------------------------
System.Memory
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.Memory.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.Private.CoreLib.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.Threading.Thread.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 6.0.1423.7402
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/Accessibility.dll
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.Numerics.Vectors.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.Collections.NonGeneric.dll
----------------------------------------
System.Net.Http
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.Net.Http.dll
----------------------------------------
System.Net.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.Net.Primitives.dll
----------------------------------------
System.Diagnostics.Tracing
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.Diagnostics.Tracing.dll
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.Diagnostics.DiagnosticSource.dll
----------------------------------------
System.Net.Security
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.Net.Security.dll
----------------------------------------
System.Security.Cryptography.X509Certificates
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.Security.Cryptography.X509Certificates.dll
----------------------------------------
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/mscorlib.dll
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.Threading.ThreadPool.dll
----------------------------------------
System.Runtime.Loader
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.Runtime.Loader.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.Resources.Extensions.dll
----------------------------------------
System.Drawing
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.1423.7402
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.Drawing.dll
----------------------------------------
System.Diagnostics.FileVersionInfo
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.Diagnostics.FileVersionInfo.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------
System.Linq.Parallel
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.Linq.Parallel.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///D:/Downloads/Stable%20Diffusion/BDTM_V1.6.5_NetCore60_AllInclude/BooruDatasetTagManager/System.Collections.Immutable.dll
----------------------------------------

************** JIT Debugging **************

**Comment by starik222** [comment]
Fixed in [1.6.6](https://github.com/starik222/BooruDatasetTagManager/releases/tag/v1.6.6)
