### ISSUE TITLE
[BUG] Add Tag window layout is overlapping and part of the tag is cut off.

### ISSUE THREAD

**Issue by jancsaw** [starik222/BooruDatasetTagManager#49]
Hello, I'm using version 1.6.5.0, and whenever I do anything that uses the 'Add Tag' window, it shows up like it does in the picture, and the first four letters of the tag I enter are cut-off.
![Screenshot - 6_11_2023 , 2_30_48 PM](https://github.com/starik222/BooruDatasetTagManager/assets/96272310/df8b0070-5237-4217-ae2f-341683e94b33)

**Comment by starik222** [comment]
Fixed in [1.6.6](https://github.com/starik222/BooruDatasetTagManager/releases/tag/v1.6.6)
