### ISSUE TITLE
When using large datasets it does not remove tags from files

### ISSUE THREAD

**Issue by Fownie** [starik222/BooruDatasetTagManager#5]
When using it on large datasets, and when selecting a common tag, then delete it, and then save, it doesnt delete the tags and the files remain unchanged.

**Comment by neojam** [comment]
How big of a dataset are we talking? 
I mostly do under 1000 images for Lora training and I didn't run into that problem yet.

**Comment by Fownie** [comment]
Weird, on 100 images its not changing any tag, im on windows 11

Enviado desde Outlook para Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by neojam** [comment]
Currently working on a 360 images dataset.
Tried adding and removing tags to all and i had no probs with it (win10).
Windows defender or Antivirus perhaps?

**Comment by Fownie** [comment]
Its strange even running it as an admin doesnt do anything i will try disabling the windows security

Enviado desde Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
