### ISSUE TITLE
bug：The process cannot access the file

### ISSUE THREAD

**Issue by wzgrx** [starik222/BooruDatasetTagManager#51]
************** 异常文本 **************
System.IO.IOException: The process cannot access the file 'D:\File\ou\12.png' because it is being used by another process.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at BooruDatasetTagManager.Extensions.GetImageFromFile(String imagePath) in M:\Dev\BooruDatasetTagManager\BooruDatasetTagManager\Extensions.cs:line 101
   at BooruDatasetTagManager.Form_preview.Show(String img) in M:\Dev\BooruDatasetTagManager\BooruDatasetTagManager\Form_preview.cs:line 32
   at BooruDatasetTagManager.Form1.ShowPreview(String img) in M:\Dev\BooruDatasetTagManager\BooruDatasetTagManager\Form1.cs:line 144
   at BooruDatasetTagManager.Form1.gridViewDS_MouseDoubleClick(Object sender, MouseEventArgs e) in M:\Dev\BooruDatasetTagManager\BooruDatasetTagManager\Form1.cs:line 1510
   at System.Windows.Forms.DataGridView.OnMouseDoubleClick(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.DataGridView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

************** 已加载的程序集 **************
System.Private.CoreLib
    程序集版本:6.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.Private.CoreLib.dll
----------------------------------------
BooruDatasetTagManager
    程序集版本:1.6.5.0
    Win32 版本:1.6.5.0
    代码库:file:///G:/Soft/BooruDatasetTagManager/BooruDatasetTagManager.dll
----------------------------------------
System.Runtime
    程序集版本:6.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    程序集版本:6.0.2.0
    Win32 版本:6.0.1423.7402
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.ComponentModel.Primitives.dll
----------------------------------------
System.Windows.Forms.Primitives
    程序集版本:6.0.2.0
    Win32 版本:6.0.1423.7402
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    程序集版本:6.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    程序集版本:6.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.Collections.Specialized.dll
----------------------------------------
System.Drawing.Common
    程序集版本:6.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.Drawing.Common.dll
----------------------------------------
System.Threading
    程序集版本:6.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    程序集版本:6.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    程序集版本:6.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.Collections.dll
----------------------------------------
Newtonsoft.Json
    程序集版本:13.0.0.0
    Win32 版本:13.0.3.27908
    代码库:file:///G:/Soft/BooruDatasetTagManager/Newtonsoft.Json.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    程序集版本:6.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.Runtime.Serialization.Formatters.dll
----------------------------------------
System.Collections.Concurrent
    程序集版本:6.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.Collections.Concurrent.dll
----------------------------------------
System.Linq.Expressions
    程序集版本:6.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.Linq.Expressions.dll
----------------------------------------
System.Runtime.Numerics
    程序集版本:6.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.Runtime.Numerics.dll
----------------------------------------
System.Private.Uri
    程序集版本:6.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.Private.Uri.dll
----------------------------------------
System.Linq
    程序集版本:6.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.Linq.dll
----------------------------------------
System.ComponentModel.TypeConverter
    程序集版本:6.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.ObjectModel
    程序集版本:6.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.ObjectModel.dll
----------------------------------------
System.Runtime.Serialization.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.Runtime.Serialization.Primitives.dll
----------------------------------------
System.Data.Common
    程序集版本:6.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.Data.Common.dll
----------------------------------------
System.Xml.ReaderWriter
    程序集版本:6.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    程序集版本:6.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.Private.Xml.dll
----------------------------------------
System.ComponentModel
    程序集版本:6.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.ComponentModel.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    程序集版本:6.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    程序集版本:6.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.Reflection.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.Reflection.Primitives.dll
----------------------------------------
System.Memory
    程序集版本:6.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.Memory.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    程序集版本:0.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.Private.CoreLib.dll
----------------------------------------
Microsoft.Win32.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    程序集版本:6.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    程序集版本:6.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.Threading.Thread.dll
----------------------------------------
Accessibility
    程序集版本:4.0.0.0
    Win32 版本:6.0.1423.7402
    代码库:file:///G:/Soft/BooruDatasetTagManager/Accessibility.dll
----------------------------------------
System.Numerics.Vectors
    程序集版本:6.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.Numerics.Vectors.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    程序集版本:6.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Collections.NonGeneric
    程序集版本:6.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.Collections.NonGeneric.dll
----------------------------------------
System.Net.Http
    程序集版本:6.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.Net.Http.dll
----------------------------------------
System.Net.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.Net.Primitives.dll
----------------------------------------
System.Diagnostics.Tracing
    程序集版本:6.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.Diagnostics.Tracing.dll
----------------------------------------
System.Diagnostics.DiagnosticSource
    程序集版本:6.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.Diagnostics.DiagnosticSource.dll
----------------------------------------
System.Net.Security
    程序集版本:6.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.Net.Security.dll
----------------------------------------
System.Security.Cryptography.X509Certificates
    程序集版本:6.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.Security.Cryptography.X509Certificates.dll
----------------------------------------
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/mscorlib.dll
----------------------------------------
System.Threading.ThreadPool
    程序集版本:6.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.Threading.ThreadPool.dll
----------------------------------------
System.Runtime.Loader
    程序集版本:6.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.Runtime.Loader.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:6.0.2.0
    Win32 版本:6.0.1423.7402
    代码库:file:///G:/Soft/BooruDatasetTagManager/zh-Hans/System.Windows.Forms.resources.dll
----------------------------------------
System.Resources.Extensions
    程序集版本:6.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.Resources.Extensions.dll
----------------------------------------
System.Drawing
    程序集版本:6.0.2.0
    Win32 版本:6.0.1423.7402
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.Drawing.dll
----------------------------------------
System.Diagnostics.FileVersionInfo
    程序集版本:6.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.Diagnostics.FileVersionInfo.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    程序集版本:6.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------
System.Linq.Parallel
    程序集版本:6.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.Linq.Parallel.dll
----------------------------------------
System.Diagnostics.StackTrace
    程序集版本:6.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    程序集版本:6.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    程序集版本:6.0.0.0
    Win32 版本:6.0.1423.7309
    代码库:file:///G:/Soft/BooruDatasetTagManager/System.Collections.Immutable.dll
----------------------------------------

************** JIT 调试 **************

**Comment by mbastias** [comment]
I'm having this problem too on last version. The preview seems to hold a previous image and then trying to switch back it gives the error.

**Comment by starik222** [comment]
Fixed in [1.6.6](https://github.com/starik222/BooruDatasetTagManager/releases/tag/v1.6.6)
