### ISSUE TITLE
[Request] Undo or "Go Back" feature

### ISSUE THREAD

**Issue by ciaduck** [starik222/BooruDatasetTagManager#55]
It would be very nice to have an "undo" or "go back" feature. Even if it's just a simple one buffer step like in `notepad.exe`.

The issue I'm having is I'm prone to loose all the tags/data for an image if I accidentally press the wrong button, or heaven forbid paste from the clip board.

Making it easier to recover from tag loss would be great. Thank you.

**Comment by starik222** [comment]
Implemented in version [2.0.0](https://github.com/starik222/BooruDatasetTagManager/releases/tag/v2.0.0)
