### ISSUE TITLE
The 'replace tag' window doesn't scale correctly

### ISSUE THREAD

**Issue by KptChaos** [starik222/BooruDatasetTagManager#58]
The 'replace tag' window doesn't scale correctly. If I scale the window, the dropdown list doesn't scale along with it (has the same initial size). Because of that if the tag is long there's no way to see full tag in the dropdown list. 
example:
https://tiny.pl/cgb9f

**Comment by starik222** [comment]
Fixed in version [1.6.7](https://github.com/starik222/BooruDatasetTagManager/releases/tag/v1.6.7)
