### ISSUE TITLE
When trying to save all dataset, I'm getting this error

### ISSUE THREAD

**Issue by L3viathn** [starik222/BooruDatasetTagManager#59]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at BooruDatasetTagManager.DatasetManager.SaveAll(Boolean fixTags) in M:\Dev\BooruDatasetTagManager\BooruDatasetTagManager\DatasetManager.cs:line 51
   at BooruDatasetTagManager.Form1.saveAllChangesToolStripMenuItem_Click(Object sender, EventArgs e) in M:\Dev\BooruDatasetTagManager\BooruDatasetTagManager\Form1.cs:line 692
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.Private.CoreLib.dll
----------------------------------------
BooruDatasetTagManager
    Assembly Version: 1.6.6.0
    Win32 Version: 1.6.6.0
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/BooruDatasetTagManager.dll
----------------------------------------
System.Runtime
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.1423.7402
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.ComponentModel.Primitives.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.1423.7402
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.Collections.Specialized.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.Drawing.Common.dll
----------------------------------------
System.Threading
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.Collections.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.3.27908
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/Newtonsoft.Json.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.Runtime.Serialization.Formatters.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.Collections.Concurrent.dll
----------------------------------------
System.Linq.Expressions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.Linq.Expressions.dll
----------------------------------------
System.Runtime.Numerics
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.Runtime.Numerics.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.Private.Uri.dll
----------------------------------------
System.Linq
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.Linq.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.ObjectModel
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.ObjectModel.dll
----------------------------------------
System.Runtime.Serialization.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.Runtime.Serialization.Primitives.dll
----------------------------------------
System.Data.Common
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.Data.Common.dll
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.Private.Xml.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.ComponentModel.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.Reflection.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.Reflection.Primitives.dll
----------------------------------------
System.Memory
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.Memory.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.Private.CoreLib.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.Threading.Thread.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 6.0.1423.7402
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/Accessibility.dll
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.Numerics.Vectors.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.Collections.NonGeneric.dll
----------------------------------------
System.Net.Http
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.Net.Http.dll
----------------------------------------
System.Net.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.Net.Primitives.dll
----------------------------------------
System.Diagnostics.Tracing
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.Diagnostics.Tracing.dll
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.Diagnostics.DiagnosticSource.dll
----------------------------------------
System.Net.Security
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.Net.Security.dll
----------------------------------------
System.Security.Cryptography.X509Certificates
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.Security.Cryptography.X509Certificates.dll
----------------------------------------
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/mscorlib.dll
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.Threading.ThreadPool.dll
----------------------------------------
System.Runtime.Loader
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.Runtime.Loader.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.Resources.Extensions.dll
----------------------------------------
System.Drawing
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.1423.7402
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.Drawing.dll
----------------------------------------
System.Diagnostics.FileVersionInfo
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.Diagnostics.FileVersionInfo.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------
System.Linq.Parallel
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.Linq.Parallel.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.1423.7309
    CodeBase: file:///C:/Users/Dante/Documents/stable-diff/LORA_Training/BDTM_V1.6.6_NetCore60_AllInclude/BooruDatasetTagManager/System.Collections.Immutable.dll
----------------------------------------

************** JIT Debugging **************

Am I going to lose all the work I just did?

**Comment by ARTIK31** [comment]
What shall I do, if I don't have DatasetManager?
![Screenshot_3](https://github.com/starik222/BooruDatasetTagManager/assets/125573485/7957f165-489a-408f-b2fd-c3e758be1014)
cs?

**Comment by starik222** [comment]
Fixed in version [1.6.7](https://github.com/starik222/BooruDatasetTagManager/releases/tag/v1.6.7)
