### ISSUE TITLE
[Request] Show image count for each tag (in All tags list) with option to sort by it

### ISSUE THREAD

**Issue by EvgeneKuklin** [starik222/BooruDatasetTagManager#60]
That would be convinient for dataset managment

**Comment by mbastias** [comment]
I second this, it helps to balance repeats and detect problems.  I also want to know if you have a donation link or similar because I definitely made money with this and I want to pay some back to you guys.

**Comment by starik222** [comment]
Implemented in version [1.7.1](https://github.com/starik222/BooruDatasetTagManager/releases/tag/v1.7.1)
