### ISSUE TITLE
[Request] add controlling weighted captions function

### ISSUE THREAD

**Issue by aDropp** [starik222/BooruDatasetTagManager#61]
I hope it can control the weight of the captions and the style is like  [this](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Features#attentionemphasis).
I test the [weighted captions](https://github.com/kohya-ss/sd-scripts/pull/336) in kohya_ss's scripts and it seems to be good, however, it is too wasted time to tag the captions one by one. So i hope you can add controlling weighted captions function.
Thank you!

**Comment by starik222** [comment]
Implemented in version [2.0.0](https://github.com/starik222/BooruDatasetTagManager/releases/tag/v2.0.0)
