### ISSUE TITLE
Application asks for elevated privileges

### ISSUE THREAD

**Issue by hofleverancier** [starik222/BooruDatasetTagManager#64]
When running BooruDatasetTagManager.exe from BDTM_V1.6.7_NetCore60_AllInclude, elevated privileges are requested, this application should not require admin rights.

![image](https://github.com/starik222/BooruDatasetTagManager/assets/10186837/5e8ef2a0-26c8-42ff-8a8a-003f56f3055f)

**Comment by starik222** [comment]
This was done in the latest update to avoid cases of missing read/delete permissions on images.

**Comment by anothertal3** [comment]
I really like the application but in my opinion that's like using a sledgehammer to crack a nut. 

Missing permissions on images should be a pretty rare case. And even then it should be quite simple to notify the user that "saving is impossible, the file might be readonly" or something similar. This should be easily solvable by them afterwards.

The security implications on the other hand are quite noteworty and questionable. I would strongly suggest to rethink that design decision.

**Comment by starik222** [comment]
> I really like the application but in my opinion that's like using a sledgehammer to crack a nut.
> 
> Missing permissions on images should be a pretty rare case. And even then it should be quite simple to notify the user that "saving is impossible, the file might be readonly" or something similar. This should be easily solvable by them afterwards.
> 
> The security implications on the other hand are quite noteworty and questionable. I would strongly suggest to rethink that design decision.

Yes, I also came to this conclusion. In the next update, the request for elevated privileges will be removed.

**Comment by anothertal3** [comment]
Thank you, glad to hear that 👍
