### ISSUE TITLE
Capital letters in tag not handeled consistently

### ISSUE THREAD

**Issue by gspawndli** [starik222/BooruDatasetTagManager#65]
Adding TAG to all images that has capital letters add the TAG with capital letters only to the image selected , all other images gets the same tag in small. The capital letters should be preserved as in the intended tag , or all tags should be small. 
![step 1-setting tag to all](https://github.com/starik222/BooruDatasetTagManager/assets/141942360/7af67bff-9387-4ece-864f-cfe7449c0674)
![step 2-Selected Photo in original capital letters](https://github.com/starik222/BooruDatasetTagManager/assets/141942360/d899dc5a-eb81-498a-a140-883cd65ef992)
![step 3 -Tag in small  letters](https://github.com/starik222/BooruDatasetTagManager/assets/141942360/c6a82f4e-f36b-4871-953e-661c575ce48b)

**Comment by starik222** [comment]
Fixed in version [1.7.1](https://github.com/starik222/BooruDatasetTagManager/releases/tag/v1.7.1)
