### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by Bunnybailey** [starik222/BooruDatasetTagManager#67]
Can anyone tell me how to use this notebook if I run stable diffusion through google colab?

**Comment by Bunnybailey** [comment]
sorry, Not notebook, but to use this dataset tag manager for training with lora's through google colab.

**Comment by starik222** [comment]
You will not be able to use BDTM in Google Collab. You must use BDTM on your computer to prepare the dataset. You can use the finished dataset for training through Google Colab.
