### ISSUE TITLE
It's hard to display the text completely when it's too long, can you add the function of auto line break?

### ISSUE THREAD

**Issue by RexLeeGrey** [starik222/BooruDatasetTagManager#68]
![image](https://github.com/starik222/BooruDatasetTagManager/assets/125941057/4fe6af6a-8a74-4166-92c5-36af34994c6d)
I want it to be able to handle natural language tags, I use "\n" in the settings but it's hard to display the text completely if it's too long, can you add automatic line breaks?

**Comment by starik222** [comment]
Implemented in version [2.0.0](https://github.com/starik222/BooruDatasetTagManager/releases/tag/v2.0.0)
