### ISSUE TITLE
Question about the Numbers

### ISSUE THREAD

**Issue by caniyabanci76** [starik222/BooruDatasetTagManager#70]
Can anyone tell me what the numbers mean in the tag drop-down list (2nd image in the readme.md) and also the numbers when multi-select is active (3rd image in the readme.md)

**Comment by starik222** [comment]
The numbers in the dropdown list show count of images with that tag on booru. This number dates back to when the tag database was made. Consider this an indicator of the tag's popularity. 
For multiple selections, the second column displays the image name.
