### ISSUE TITLE
It's slow to find the tags by scrolling the mouse, can you change the display of all tabs to a table? so that user can find the tags by muscle memory

### ISSUE THREAD

**Issue by zihualiu1997** [starik222/BooruDatasetTagManager#71]
It's hard to find the tags by scrolling the mouse, can you change the display of all tabs to a table? so that user can find the tags by muscle memory

**Comment by starik222** [comment]
Please clarify your issue. The list of all tags has a quick search and filtering, and from the list of image tags you can quickly find the desired tag in the list of all tags. What the tabs are you talking about?

**Comment by zihualiu1997** [comment]
Thank s for your reply, I'm not sure anybody needs this feature. What I am asking is when I do the tagging work, when there are more tags than can be displayed on one page, I need to keep scrolling the mouse back and forth and double clicking to select the tag I need.(I feel it is slow because not easy to see when tabs are scrolling quickly). I think that if the all tag interface can be a table that do not need to scrolling, I can find the tag in the same position when working, it will be faster when tagging a large number of pictures.
![1](https://github.com/starik222/BooruDatasetTagManager/assets/144887244/d62a13f5-f78f-43b9-8e35-74c0ef9cfb87)
![2](https://github.com/starik222/BooruDatasetTagManager/assets/144887244/65279d37-51aa-4f07-a11c-048e5dacff99)

**Comment by starik222** [comment]
I understand, but such a change will not be made. This will be the same table, only with horizontal scrolling. I can see from your screenshots that you are creating a dataset from realistic images. That is, you use long tags of several words. In the next updates, lines will be wrapped in cells to fully display text. But if you make a table with horizontal scrolling, then there will be no line breaks, but you will get very wide columns. The result will be a very wide table in which it will be very difficult to find something. If you know the tag you're looking for, you can simply start typing in the table of all tags and the selection will immediately jump to it (see second image in the readme)

**Comment by zihualiu1997** [comment]
Got it. Thank you very much for your work.
