### ISSUE TITLE
please

### ISSUE THREAD

**Issue by w844741652** [starik222/BooruDatasetTagManager#74]
I hope the functions of batch selection and position adjustment can be added. For example, I have 100 pictures, among which 40 pictures are 1girl, but it is tiring to adjust the tag position one by one at the bottom of all the tags.

**Comment by starik222** [comment]
Maybe I didn't fully understand your problem, but you can filter images by tag, and after that use the function of adding a tag to the filtered images. The logic of the program is such that if the tag to be added already exists, then it will simply change the position to the one selected in the add tag window.
