### ISSUE TITLE
Why on earth does this require administrator privileges to run?

### ISSUE THREAD

**Issue by fake-name** [starik222/BooruDatasetTagManager#75]
There are zero good reasons for something like this to require admin privileges, and it's a potential huge security issue. 

Dropping the requirement from the `app.manifest` yields a project that still runs fine.

**Comment by starik222** [comment]
check [this](https://github.com/starik222/BooruDatasetTagManager/commit/04eff1dbbf527dd3673e84aeac0b733d604ffb8b)
