### ISSUE TITLE
Autogenerated tags include tags already present on image

### ISSUE THREAD

**Issue by fake-name** [starik222/BooruDatasetTagManager#81]
Basically the title. If I use the interrogator to infer the tags for an image, the tag list shown from the interrogator includes tags that are already present on the image. 

I'm not sure if this is intentional or not, but I hope not. I generally use the interrogator to flesh out a already-tagged dataset, and showing tags that are already present makes this a lot harder.

**Comment by fake-name** [comment]
Actually, this seems to be how the "All Tags" view works too. It'd be nice if that listing also excluded tags already resent on the image as well.

**Comment by starik222** [comment]
Now the generation of tags completely replaces the already existing tags on the image. Do you want new tags to simply be added to existing ones?

**Comment by fake-name** [comment]
Ok, I think this is mostly just a mismatchin how I think of the UI, versus how you've planned it:

![image](https://github.com/starik222/BooruDatasetTagManager/assets/1401239/f8d71c5f-0a09-49f2-ad00-4d5300c7088f)

The middle column are tags for the current image. The right-hand column is, in my idea, tags that _could be_ applied to the current image. Critically, this should not include any tags that are already on the image. 

At least for the autotagging context, having a tag available to add to the image when it's already present on the image doesn't really make sense. For the all-tags view, I think the all-tags view shouldn't show a tag that is already on the image, but I'm less attached to that idea.

**Comment by starik222** [comment]
Okay, I'll add a feature to only show missing tags. Regarding the list of all tags, I did not pay much attention to it, but as it turned out, in the current implementation it is too buggy and incompatible with the changes that were made to the data set. Therefore, it will have to be completely rewritten, and I will try to add the function of hiding existing tags on the image as a separate setting.

**Comment by starik222** [comment]
Check the latest commits, I added a setting to display the result. Also, in theory, there should be no problems with the DeduplicateTags function now.

**Comment by starik222** [comment]
Implemented in [2.0.1](https://github.com/starik222/BooruDatasetTagManager/releases/tag/v2.0.1)

**Comment by fake-name** [comment]
Woot!
