### ISSUE TITLE
[BUG]  Issues when adding new tags.

### ISSUE THREAD

**Issue by jancsaw** [starik222/BooruDatasetTagManager#82]
Hello, in version 2.0.0, I run into two issues where adding new tags won't update properly in the 'All tags' window. 

The first issue is that if I add a new tag to an image in the 'Image Tags' window, the list in the 'All Tags' window won't update with the new tags. The only way I've found to get around this is by adding or deleting a tag with any of the buttons next to the 'All Tags' window, then clicking the 'Switch all tags/common tags mode' button twice, after which, my tags from the 'Image Tags' window will finally show up in 'All Tags'. 

The second issue I ran into is that when adding a new tag through either the 'Add Tag to All' or the 'Add Tag to Filtered' button, the tag will get added to the list, but it won't be sorted alphabetically until I click the 'Switch all tags/common tags mode' button twice.

**Comment by madrooky** [comment]
Same issue. Another workaround is simply safe all changes and reload the set.

**Comment by starik222** [comment]
Fixed in [2.0.1](https://github.com/starik222/BooruDatasetTagManager/releases/tag/v2.0.1)
