### ISSUE TITLE
似乎图像很多时会炸

### ISSUE THREAD

**Issue by jxhxgt** [starik222/BooruDatasetTagManager#84]
有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.AggregateException: One or more errors occurred. (Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index'))
 ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.CollectionBase.System.Collections.IList.get_Item(Int32 index)
   at BooruDatasetTagManager.EditableTagList.DeduplicateTags() in M:\Dev\BooruDatasetTagManager\BooruDatasetTagManager\EditableTagList.cs:line 212
   at BooruDatasetTagManager.EditableTagList.ToString() in M:\Dev\BooruDatasetTagManager\BooruDatasetTagManager\EditableTagList.cs:line 73
   at System.String.JoinCore(ReadOnlySpan`1 separator, Object[] values)
   at BooruDatasetTagManager.DatasetManager.DataItem.ToString() in M:\Dev\BooruDatasetTagManager\BooruDatasetTagManager\DatasetManager.cs:line 402
   at BooruDatasetTagManager.DatasetManager.DataItem.GetHashCode() in M:\Dev\BooruDatasetTagManager\BooruDatasetTagManager\DatasetManager.cs:line 407
   at BooruDatasetTagManager.DatasetManager.DataItem.GetTagsFromFile() in M:\Dev\BooruDatasetTagManager\BooruDatasetTagManager\DatasetManager.cs:line 398
   at BooruDatasetTagManager.DatasetManager.DataItem..ctor(String imagePath, Int32 imageSize) in M:\Dev\BooruDatasetTagManager\BooruDatasetTagManager\DatasetManager.cs:line 362
   at BooruDatasetTagManager.DatasetManager.<>c__DisplayClass25_0.<LoadFromFolder>b__2(String x) in M:\Dev\BooruDatasetTagManager\BooruDatasetTagManager\DatasetManager.cs:line 276
   at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)
   at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Linq.Parallel.QueryTask.<>c.<.cctor>b__10_0(Object o)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.SpoolingTask.SpoolForAll[TInputOutput,TIgnoreKey](QueryTaskGroupState groupState, PartitionedStream`2 partitions, TaskScheduler taskScheduler)
   at System.Linq.Parallel.DefaultMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute()
   at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
   at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
   at System.Linq.Parallel.ForAllOperator`1.WrapPartitionedStream[TKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, Boolean preferStriping, QuerySettings settings)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
   at System.Linq.Parallel.ListQueryResults`1.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
   at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
   at System.Linq.Parallel.ForAllOperator`1.RunSynchronously()
   at System.Linq.ParallelEnumerable.ForAll[TSource](ParallelQuery`1 source, Action`1 action)
   at BooruDatasetTagManager.DatasetManager.LoadFromFolder(String folder) in M:\Dev\BooruDatasetTagManager\BooruDatasetTagManager\DatasetManager.cs:line 274
   at BooruDatasetTagManager.MainForm.openFolderToolStripMenuItem_Click(Object sender, EventArgs e) in M:\Dev\BooruDatasetTagManager\BooruDatasetTagManager\Form1.cs:line 100
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

************** 已加载的程序集 **************
System.Private.CoreLib
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Private.CoreLib.dll
----------------------------------------
BooruDatasetTagManager
    程序集版本:2.0.0.0
    Win32 版本:2.0.0.0
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/BooruDatasetTagManager.dll
----------------------------------------
System.Runtime
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    程序集版本:6.0.2.0
    Win32 版本:6.0.2123.36406
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.ComponentModel.Primitives.dll
----------------------------------------
System.Windows.Forms.Primitives
    程序集版本:6.0.2.0
    Win32 版本:6.0.2123.36406
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Collections.Specialized.dll
----------------------------------------
System.Drawing.Common
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Drawing.Common.dll
----------------------------------------
System.Threading
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Collections.dll
----------------------------------------
Newtonsoft.Json
    程序集版本:13.0.0.0
    Win32 版本:13.0.3.27908
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/Newtonsoft.Json.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Runtime.Serialization.Formatters.dll
----------------------------------------
System.Collections.Concurrent
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Collections.Concurrent.dll
----------------------------------------
System.Linq.Expressions
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Linq.Expressions.dll
----------------------------------------
System.Runtime.Numerics
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Runtime.Numerics.dll
----------------------------------------
System.Private.Uri
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Private.Uri.dll
----------------------------------------
System.Linq
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Linq.dll
----------------------------------------
System.ComponentModel.TypeConverter
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.ObjectModel
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.ObjectModel.dll
----------------------------------------
System.Runtime.Serialization.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Runtime.Serialization.Primitives.dll
----------------------------------------
System.Data.Common
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Data.Common.dll
----------------------------------------
System.Xml.ReaderWriter
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Private.Xml.dll
----------------------------------------
System.ComponentModel
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.ComponentModel.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.Reflection.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Reflection.Primitives.dll
----------------------------------------
System.Memory
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Memory.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    程序集版本:0.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Private.CoreLib.dll
----------------------------------------
System.Drawing
    程序集版本:6.0.2.0
    Win32 版本:6.0.2123.36406
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Drawing.dll
----------------------------------------
Microsoft.Win32.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Threading.Thread.dll
----------------------------------------
Accessibility
    程序集版本:4.0.0.0
    Win32 版本:6.0.2123.36406
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/Accessibility.dll
----------------------------------------
BooruDatasetTagManager.resources
    程序集版本:2.0.0.0
    Win32 版本:2.0.0.0
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/zh-CN/BooruDatasetTagManager.resources.dll
----------------------------------------
System.Numerics.Vectors
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Numerics.Vectors.dll
----------------------------------------
TabControl
    程序集版本:2.1.2.0
    Win32 版本:1.0.0.0
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/TabControl.dll
----------------------------------------
PagedControl
    程序集版本:2.2.0.0
    Win32 版本:1.0.0.0
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/PagedControl.dll
----------------------------------------
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/mscorlib.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Collections.NonGeneric
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Collections.NonGeneric.dll
----------------------------------------
System.Net.Http
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Net.Http.dll
----------------------------------------
System.Net.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Net.Primitives.dll
----------------------------------------
System.Diagnostics.Tracing
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Diagnostics.Tracing.dll
----------------------------------------
System.Diagnostics.DiagnosticSource
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Diagnostics.DiagnosticSource.dll
----------------------------------------
System.Net.Security
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Net.Security.dll
----------------------------------------
System.Security.Cryptography.X509Certificates
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Security.Cryptography.X509Certificates.dll
----------------------------------------
System.Threading.ThreadPool
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Threading.ThreadPool.dll
----------------------------------------
Grpc.Net.Client
    程序集版本:2.0.0.0
    Win32 版本:2.57.0.0
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/Grpc.Net.Client.dll
----------------------------------------
Grpc.Core.Api
    程序集版本:2.0.0.0
    Win32 版本:2.57.0.0
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/Grpc.Core.Api.dll
----------------------------------------
netstandard
    程序集版本:2.1.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/netstandard.dll
----------------------------------------
Microsoft.Extensions.Logging.Abstractions
    程序集版本:6.0.0.0
    Win32 版本:6.0.21.52210
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/Microsoft.Extensions.Logging.Abstractions.dll
----------------------------------------
Grpc.Net.Common
    程序集版本:2.0.0.0
    Win32 版本:2.57.0.0
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/Grpc.Net.Common.dll
----------------------------------------
System.IO.Compression
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.IO.Compression.dll
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
System.Runtime.Loader
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Runtime.Loader.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:6.0.2.0
    Win32 版本:6.0.2123.36406
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/zh-Hans/System.Windows.Forms.resources.dll
----------------------------------------
System.Core
    程序集版本:4.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Core.dll
----------------------------------------
System.Resources.Extensions
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Resources.Extensions.dll
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.dll
----------------------------------------
System.Diagnostics.FileVersionInfo
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Diagnostics.FileVersionInfo.dll
----------------------------------------
System.Diagnostics.Process
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Diagnostics.Process.dll
----------------------------------------
System.Net.Sockets
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Net.Sockets.dll
----------------------------------------
System.Threading.Overlapped
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Threading.Overlapped.dll
----------------------------------------
System.Net.NameResolution
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Net.NameResolution.dll
----------------------------------------
System.Security.Cryptography.Primitives
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Security.Cryptography.Primitives.dll
----------------------------------------
System.Security.Principal.Windows
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Security.Principal.Windows.dll
----------------------------------------
System.Security.Claims
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Security.Claims.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------
System.Linq.Parallel
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Linq.Parallel.dll
----------------------------------------
System.Text.RegularExpressions
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Text.RegularExpressions.dll
----------------------------------------
System.Diagnostics.StackTrace
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    程序集版本:6.0.0.0
    Win32 版本:6.0.2123.36311
    代码库:file:///E:/jiaoben/BDTM_V2.0.0_NetCore60_AllInclude/BooruDatasetTagManager/System.Collections.Immutable.dll
----------------------------------------

**Comment by starik222** [comment]
Fixed in [2.0.1](https://github.com/starik222/BooruDatasetTagManager/releases/tag/v2.0.1)
