### ISSUE TITLE
[Request] Focus Image Tags panel on "Add new tag" action

### ISSUE THREAD

**Issue by ThereforeGames** [starik222/BooruDatasetTagManager#86]
Hi,

Great software! It speeds up my captioning process tremendously. I have a few suggestions for improving it further, I'll submit each one as a separate issue.

This one is simple: when you press Ctrl+E to add a new tag, the program should automatically focus the Image Tags panel - I can't think of a scenario where you *wouldn't* want this to occur.

I implemented this in my own copy by changing the following line in `Form1.cs`:

```
cmds["BtnTagAdd"] = delegate () { BtnTagAdd.PerformClick(); TagsFocus(); };
```

Which seems to do the trick.

**Comment by starik222** [comment]
Implemented in [2.0.1](https://github.com/starik222/BooruDatasetTagManager/releases/tag/v2.0.1)
