### ISSUE TITLE
[Request] Docked preview panel

### ISSUE THREAD

**Issue by ThereforeGames** [starik222/BooruDatasetTagManager#88]
Hi,

At the moment, I find myself arranging the preview and app windows to each occupy 50% width using the Snap feature in Windows.

It works, but it's a bit cumbersome. It would be nice if we could dock the preview panel into the main application, similar to the Preview feature in Windows explorer (Alt+P).

**EDIT:** On a related note, the topmost behavior of the popout preview gets in the way of switching between apps. I think there should be a way to toggle this, but for now I went ahead and removed `TopMost = true;` from my copy in the `Form_preview.Designer.cs` script.

**Comment by starik222** [comment]
Implemented in [2.1.0](https://github.com/starik222/BooruDatasetTagManager/releases/tag/v2.1.0)
