### ISSUE TITLE
Regression, tag list not refreshing when adding new tag

### ISSUE THREAD

**Issue by WarAnakin** [starik222/BooruDatasetTagManager#90]
When adding a new tag the "All tags" list is not being automatically refreshed as in previous versions.
Also, how could I get in touch with the creator. I use this software quite frequently to caption my datasets for training checkpoints and LORAs and I have some ideas on how to help do things quicker and more efficiently.

**Comment by starik222** [comment]
Fixed in [2.0.1](https://github.com/starik222/BooruDatasetTagManager/releases/tag/v2.0.1)
