### ISSUE TITLE
Crash on "add tag" hotkey

### ISSUE THREAD

**Issue by Xavia1991** [starik222/BooruDatasetTagManager#96]
I added multiple tags with standard hotkey ctrl e. on the 10th or so suddenly I got flooded with errors and the program was unusable until restarted.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ComponentModel.InvalidAsynchronousStateException: List desynchronization detected!
   at BooruDatasetTagManager.EditableTagList.OnListChanged(ListChangedEventArgs ev) in J:\Dev\BooruDatasetTagManager\BooruDatasetTagManager\EditableTagList.cs:line 552
   at BooruDatasetTagManager.EditableTagList.OnInsertComplete(Int32 index, Object value) in J:\Dev\BooruDatasetTagManager\BooruDatasetTagManager\EditableTagList.cs:line 582
   at System.Collections.CollectionBase.System.Collections.IList.Insert(Int32 index, Object value)
   at BooruDatasetTagManager.EditableTagList.InsertNew(Int32 index) in J:\Dev\BooruDatasetTagManager\BooruDatasetTagManager\EditableTagList.cs:line 438
   at BooruDatasetTagManager.MainForm.AddNewRow() in J:\Dev\BooruDatasetTagManager\BooruDatasetTagManager\Form1.cs:line 365
   at BooruDatasetTagManager.MainForm.BtnAddTag_Clicked(Object sender, EventArgs e) in J:\Dev\BooruDatasetTagManager\BooruDatasetTagManager\Form1.cs:line 326
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.PerformClick()
   at BooruDatasetTagManager.MainForm.<InitHotkeyCommands>b__121_9() in J:\Dev\BooruDatasetTagManager\BooruDatasetTagManager\Form1.cs:line 1656
   at BooruDatasetTagManager.MainForm.ProcessCmdKey(Message& msg, Keys keyData) in J:\Dev\BooruDatasetTagManager\BooruDatasetTagManager\Form1.cs:line 1710
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.ContainerControl.ProcessCmdKey(Message& msg, Keys keyData)
   at System.Windows.Forms.Control.PreProcessMessage(Message& msg)
   at System.Windows.Forms.Control.PreProcessControlMessageInternal(Control target, Message& msg)
   at System.Windows.Forms.Application.ThreadContext.PreTranslateMessage(MSG& msg)

************** Loaded Assemblies **************
System.Private.CoreLib
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Private.CoreLib.dll
----------------------------------------
BooruDatasetTagManager
    Assembly Version: 2.0.1.0
    Win32 Version: 2.0.1.0
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/BooruDatasetTagManager.dll
----------------------------------------
System.Runtime
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.2123.36406
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.ComponentModel.Primitives.dll
----------------------------------------
System.Windows.Forms.Primitives
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.2123.36406
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Collections.Specialized.dll
----------------------------------------
System.Drawing.Common
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Drawing.Common.dll
----------------------------------------
System.Threading
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Threading.dll
----------------------------------------
System.Diagnostics.TraceSource
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Diagnostics.TraceSource.dll
----------------------------------------
System.Collections
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Collections.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 13.0.0.0
    Win32 Version: 13.0.3.27908
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/Newtonsoft.Json.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Runtime.Serialization.Formatters.dll
----------------------------------------
System.Collections.Concurrent
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Collections.Concurrent.dll
----------------------------------------
System.Linq.Expressions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Linq.Expressions.dll
----------------------------------------
System.Runtime.Numerics
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Runtime.Numerics.dll
----------------------------------------
System.Private.Uri
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Private.Uri.dll
----------------------------------------
System.Linq
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Linq.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.ObjectModel
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.ObjectModel.dll
----------------------------------------
System.Runtime.Serialization.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Runtime.Serialization.Primitives.dll
----------------------------------------
System.Data.Common
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Data.Common.dll
----------------------------------------
System.Xml.ReaderWriter
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Private.Xml.dll
----------------------------------------
System.ComponentModel
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.ComponentModel.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.Reflection.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Reflection.Primitives.dll
----------------------------------------
System.Memory
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Memory.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Private.CoreLib.dll
----------------------------------------
System.Drawing
    Assembly Version: 6.0.2.0
    Win32 Version: 6.0.2123.36406
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Drawing.dll
----------------------------------------
Microsoft.Win32.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/Microsoft.Win32.Primitives.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Threading.Thread
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Threading.Thread.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 6.0.2123.36406
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/Accessibility.dll
----------------------------------------
BooruDatasetTagManager.resources
    Assembly Version: 2.0.1.0
    Win32 Version: 2.0.1.0
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/en-US/BooruDatasetTagManager.resources.dll
----------------------------------------
System.Numerics.Vectors
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Numerics.Vectors.dll
----------------------------------------
TabControl
    Assembly Version: 2.1.2.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/TabControl.dll
----------------------------------------
PagedControl
    Assembly Version: 2.2.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/PagedControl.dll
----------------------------------------
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/mscorlib.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.Collections.NonGeneric
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Collections.NonGeneric.dll
----------------------------------------
System.Net.Http
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Net.Http.dll
----------------------------------------
System.Net.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Net.Primitives.dll
----------------------------------------
System.Diagnostics.Tracing
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Diagnostics.Tracing.dll
----------------------------------------
System.Diagnostics.DiagnosticSource
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Diagnostics.DiagnosticSource.dll
----------------------------------------
System.Net.Security
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Net.Security.dll
----------------------------------------
System.Security.Cryptography.X509Certificates
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Security.Cryptography.X509Certificates.dll
----------------------------------------
System.Threading.ThreadPool
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Threading.ThreadPool.dll
----------------------------------------
Grpc.Net.Client
    Assembly Version: 2.0.0.0
    Win32 Version: 2.57.0.0
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/Grpc.Net.Client.dll
----------------------------------------
Grpc.Core.Api
    Assembly Version: 2.0.0.0
    Win32 Version: 2.57.0.0
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/Grpc.Core.Api.dll
----------------------------------------
netstandard
    Assembly Version: 2.1.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/netstandard.dll
----------------------------------------
Microsoft.Extensions.Logging.Abstractions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.21.52210
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/Microsoft.Extensions.Logging.Abstractions.dll
----------------------------------------
Grpc.Net.Common
    Assembly Version: 2.0.0.0
    Win32 Version: 2.57.0.0
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/Grpc.Net.Common.dll
----------------------------------------
System.IO.Compression
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.IO.Compression.dll
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
System.Runtime.Loader
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Runtime.Loader.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Core.dll
----------------------------------------
System.Resources.Extensions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Resources.Extensions.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.dll
----------------------------------------
System.Diagnostics.FileVersionInfo
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Diagnostics.FileVersionInfo.dll
----------------------------------------
System.Diagnostics.Process
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Diagnostics.Process.dll
----------------------------------------
System.Net.Sockets
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Net.Sockets.dll
----------------------------------------
System.Threading.Overlapped
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Threading.Overlapped.dll
----------------------------------------
System.Net.NameResolution
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Net.NameResolution.dll
----------------------------------------
System.Security.Cryptography.Primitives
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Security.Cryptography.Primitives.dll
----------------------------------------
System.Security.Principal.Windows
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Security.Principal.Windows.dll
----------------------------------------
System.Security.Claims
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Security.Claims.dll
----------------------------------------
System.Security.Cryptography.Encoding
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Security.Cryptography.Encoding.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------
System.Linq.Parallel
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Linq.Parallel.dll
----------------------------------------
System.Text.RegularExpressions
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Text.RegularExpressions.dll
----------------------------------------
System.Diagnostics.StackTrace
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Reflection.Metadata
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Assembly Version: 6.0.0.0
    Win32 Version: 6.0.2123.36311
    CodeBase: file:///C:/Users/chris/Pictures/booru%20tagmanager/BooruDatasetTagManager/System.Collections.Immutable.dll
----------------------------------------

************** JIT Debugging **************

**Comment by starik222** [comment]
Tell me, how often do you get this error? Also, do you know the sequence of actions that leads to this error, or is it happening to you randomly?

**Comment by starik222** [comment]
Fixed in [2.0.2](https://github.com/starik222/BooruDatasetTagManager/releases/tag/v2.0.2)
