### ISSUE TITLE
Common Tags shows no tags

### ISSUE THREAD

**Issue by TomKranenburg** [starik222/BooruDatasetTagManager#99]
All tags works fine, but common tags shows an empty box when you load a dataset. Why?

**Comment by TomKranenburg** [comment]
Still not showing for me I'm afraid.

**Comment by starik222** [comment]
> Still not showing for me I'm afraid.

Can you give an example of a data set with which common tags are not displayed? Or does some procedure lead to the fact that common tags are not displayed for you? Turn on tag count display and check that the total tag count matches the image count. I tested the common tag list for a long time and did not find any problems, but since the algorithm for displaying the common tag list was completely rewritten, I am afraid that there may be errors in it that I could not find. Therefore, I hope that you will give a concrete example.

**Comment by djinteractive1** [comment]
I can't figure out it's purpose. And I don't see any documentation on the feature. Nothing shows up there for me either.  I highlight a tag and go to common on nothing shows up.  Or if this is some type of favorites so I don't have to scroll up and down the all menu (which if it isn't is something that would be great) I don't know how to add the terms to the list.  I saw something about a list.tag file, I created it but the file just got appended with {\rtf1}. I tried to add stuff in there but nothing worked.

**Comment by starik222** [comment]
> I can't figure out it's purpose. And I don't see any documentation on the feature. Nothing shows up there for me either. I highlight a tag and go to common on nothing shows up. Or if this is some type of favorites so I don't have to scroll up and down the all menu (which if it isn't is something that would be great) I don't know how to add the terms to the list. I saw something about a list.tag file, I created it but the file just got appended with {\rtf1}. I tried to add stuff in there but nothing worked.

Common tags displays only those tags that are present in all images. Try adding some tag to all images, this tag will appear in the list of common tags.

**Comment by TomKranenburg** [comment]
Sorry @starik222. I have been really busy with work swamping me and Christmas.

I assumed that's how it worked. I was getting nothing the same as @djinteractive1. I will say this I'm trying to edit about 3500 images at the same time. This is a lot obviously but it's kind of why I need your app. Perhaps this is too much for the application to handle if @djinteractive1 is using a similarly large(for a LoRA) data set.

I just want to say your app is great. Actually I've tried every single application made for this purpose and your one is the only one that will even attempt to edit the tags on a data set this size. The others either crash or won't even load subfolders.

**Comment by TomKranenburg** [comment]
> I agree this is the best app of it's kind. Favourites is better then a tab for everything you already have. Trying a checkpoint with 250k+ images. Obviously I need something to do a bulk set. There are issues that I work around with multiple tagging but it would be great to have a place where "favourites" or user chosen tags can be placed on their own.

I think it must be that then. @starik222  Probably just a big data sets crashing the common tags function?

It's unfortunate as that's the one I really need.

**Comment by starik222** [comment]
> I agree this is the best app of it's kind. Favorites is better then a tab for everything you already have. Trying a checkpoint with 250k+ images. Obviously I need somthing to do a bulk set. There are issues that I work around with multiple tagging but it would be great to have a place where "favorites" or user chosen tags can be placed on their own.

The favorites feature (or rather, the feature of custom tag sets) is planned, but for now I'm fixing bugs. As soon as the application works stably, it will be possible to think about new functionality.

**Comment by starik222** [comment]
> Probably just a big data sets crashing the common tags function?

This is a test on 6k images. test1 is present in all images, test2 is removed from one image. Or do you mean something else?
![](https://github.com/starik222/BooruDatasetTagManager/assets/1236582/d6d81998-19b0-4a66-acf1-1548e969e147)
